import { forwardRef, ButtonHTMLAttributes } from 'react';
import { cn } from '@/lib/cn';
import { Loader2 } from 'lucide-react'; type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
type ButtonSize = 'xs' | 'sm' | 'md' | 'lg'; interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { variant?: ButtonVariant; size?: ButtonSize; isLoading?: boolean; leftIcon?: React.ReactNode; rightIcon?: React.ReactNode; fullWidth?: boolean; asChild?: boolean;
} const variantStyles: Record<ButtonVariant, string> = { primary: 'bg-[#111111] text-white font-semibold hover:bg-black active:bg-gray-900 ' + 'focus-visible:ring-[#111111] shadow-sm ' + 'border border-[#111111]', secondary: 'bg-white text-[#111111] font-semibold hover:bg-gray-50 active:bg-gray-100 ' + 'focus-visible:ring-gray-300 border border-gray-200', outline: 'border border-gray-200 bg-white text-[#444444] font-medium ' + 'hover:bg-gray-50 hover:border-gray-300 active:bg-gray-100 ' + 'focus-visible:ring-gray-300', ghost: 'text-[#444444] font-medium hover:bg-gray-50 active:bg-gray-100 ' + 'focus-visible:ring-gray-300', danger: 'bg-red-600 text-white font-semibold hover:bg-red-700 active:bg-red-800 ' + 'focus-visible:ring-red-500 shadow-sm ' + 'border border-red-700',
}; const sizeStyles: Record<ButtonSize, string> = { xs: 'h-7 px-2.5 text-xs gap-1', sm: 'h-8 px-3.5 text-sm gap-1.5', md: 'h-10 px-4 text-sm gap-2', lg: 'h-11 px-5 text-base gap-2',
}; export const buttonClassName = ( variant: ButtonVariant, size: ButtonSize, fullWidth: boolean, className?: string
) => cn( 'inline-flex items-center justify-center rounded-xl transition-all duration-150', 'focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2', 'disabled:opacity-50 disabled:cursor-not-allowed disabled:pointer-events-none', 'select-none', variantStyles[variant], sizeStyles[size], fullWidth && 'w-full', className ); export const Button = forwardRef<HTMLButtonElement, ButtonProps>( ( { variant = 'primary', size = 'md', isLoading = false, leftIcon, rightIcon, fullWidth = false, disabled, className, children, asChild: _asChild, ...props }, ref ) => { const isDisabled = disabled || isLoading; return ( <button ref={ref} disabled={isDisabled} className={buttonClassName(variant, size, fullWidth, className)} {...props} > {isLoading ? ( <Loader2 className="h-4 w-4 animate-spin" /> ) : leftIcon ? ( <span className="shrink-0">{leftIcon}</span> ) : null} <span>{children}</span> {!isLoading && rightIcon ? ( <span className="shrink-0">{rightIcon}</span> ) : null} </button> ); }
); Button.displayName = 'Button';
