'use client'; import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { GraduationCap, User, Mail, Lock, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { useAuthStore } from '@/features/auth/authStore';
import { SignupCredentials } from '@/types/auth';
import toast from 'react-hot-toast'; const signupSchema = z .object({ name: z.string().min(2, 'Name must be at least 2 characters'), email: z.string().email('Enter a valid email address'), password: z.string().min(8, 'Password must be at least 8 characters'), confirmPassword: z.string(), }) .refine((data) => data.password === data.confirmPassword, { message: "Passwords don't match", path: ['confirmPassword'], }); export default function SignupPage() { const router = useRouter(); const { signup, isLoading } = useAuthStore(); const { register, handleSubmit, formState: { errors }, } = useForm<SignupCredentials>({ resolver: zodResolver(signupSchema), }); const onSubmit = async (data: SignupCredentials) => { try { await signup(data); toast.success('Account created! Welcome aboard 🎓'); router.push('/'); } catch (err) { if (err instanceof Error) toast.error(err.message); } }; return ( <div className="min-h-[calc(100vh-64px)] flex items-center justify-center px-4 py-12 bg-gray-50 "> <div className="w-full max-w-sm"> <div className="flex justify-center mb-8"> <div className="w-12 h-12 bg-[#111111] rounded-2xl flex items-center justify-center shadow-lg"> <GraduationCap className="h-7 w-7 text-white" /> </div> </div> <div className="card p-8"> <div className="text-center mb-8"> <h1 className="text-2xl font-bold text-[#111111] mb-1">Create account</h1> <p className="text-sm text-[#6b7280] ">Join thousands of students on CollegeDiscover</p> </div> <form onSubmit={handleSubmit(onSubmit)} className="space-y-4"> <Input id="signup-name" label="Full name" type="text" placeholder="John Doe" leftIcon={<User className="h-4 w-4" />} error={errors.name?.message} {...register('name')} /> <Input id="signup-email" label="Email address" type="email" placeholder="you@example.com" leftIcon={<Mail className="h-4 w-4" />} error={errors.email?.message} {...register('email')} /> <Input id="signup-password" label="Password" type="password" placeholder="Min 8 characters" leftIcon={<Lock className="h-4 w-4" />} error={errors.password?.message} hint="At least 8 characters" {...register('password')} /> <Input id="signup-confirm-password" label="Confirm password" type="password" placeholder="Re-enter your password" leftIcon={<Lock className="h-4 w-4" />} error={errors.confirmPassword?.message} {...register('confirmPassword')} /> <Button type="submit" variant="primary" size="md" fullWidth isLoading={isLoading} rightIcon={<ArrowRight className="h-4 w-4" />} id="signup-submit-btn" > Create Account </Button> </form> <p className="text-center text-sm text-[#6b7280] mt-6"> Already have an account?{' '} <Link href="/auth/login" className="text-[#111111] font-medium hover:underline"> Sign in </Link> </p> </div> </div> </div> );
}
