'use client'; import Link from 'next/link';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { GraduationCap, Mail, ArrowRight, CheckCircle } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { authService } from '@/backend/services/authService';
import toast from 'react-hot-toast'; const forgotSchema = z.object({ email: z.string().email('Enter a valid email address'),
}); type ForgotForm = { email: string }; export default function ForgotPasswordPage() { const [sent, setSent] = useState(false); const [isLoading, setIsLoading] = useState(false); const { register, handleSubmit, formState: { errors }, } = useForm<ForgotForm>({ resolver: zodResolver(forgotSchema) }); const onSubmit = async (data: ForgotForm) => { setIsLoading(true); try { const result = await authService.forgotPassword(data.email); setSent(true); toast.success(result.message); } catch { toast.error('Something went wrong. Please try again.'); } finally { setIsLoading(false); } }; return ( <div className="min-h-[calc(100vh-64px)] flex items-center justify-center px-4 py-12 bg-gray-50 "> <div className="w-full max-w-sm"> <div className="flex justify-center mb-8"> <div className="w-12 h-12 bg-[#111111] rounded-2xl flex items-center justify-center shadow-lg"> <GraduationCap className="h-7 w-7 text-white" /> </div> </div> <div className="card p-8"> {sent ? ( <div className="text-center py-4"> <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4"> <CheckCircle className="h-8 w-8 text-green-600 " /> </div> <h2 className="text-xl font-bold text-[#111111] mb-2">Check your email</h2> <p className="text-sm text-[#6b7280] mb-6"> If that email exists, we&apos;ve sent a password reset link. Check your inbox. </p> <Link href="/auth/login" className="text-sm text-[#111111] font-medium hover:underline"> Back to login </Link> </div> ) : ( <> <div className="text-center mb-8"> <h1 className="text-2xl font-bold text-[#111111] mb-1">Forgot password?</h1> <p className="text-sm text-[#6b7280] "> Enter your email and we&apos;ll send you a reset link </p> </div> <form onSubmit={handleSubmit(onSubmit)} className="space-y-4"> <Input id="forgot-email" label="Email address" type="email" placeholder="you@example.com" leftIcon={<Mail className="h-4 w-4" />} error={errors.email?.message} {...register('email')} /> <Button type="submit" variant="primary" size="md" fullWidth isLoading={isLoading} rightIcon={<ArrowRight className="h-4 w-4" />} id="forgot-submit-btn" > Send Reset Link </Button> </form> <p className="text-center text-sm text-[#6b7280] mt-6"> <Link href="/auth/login" className="text-[#111111] font-medium hover:underline"> ← Back to login </Link> </p> </> )} </div> </div> </div> );
}
